### ISSUE TITLE
AX 2012 HR definition of Worker Status

### ISSUE THREAD

**Issue by DavidJohnStokes** [MicrosoftDocs/MicrosoftCollaboratePortal#138] opened 2019-02-05 14:59 UTC
[CAS-84956 Worker Status definition.docx](https://github.com/MicrosoftDocs/MicrosoftCollaboratePortal/files/2832568/CAS-84956.Worker.Status.definition.docx)

https://community.dynamics.com/ax/f/33/t/263055

The note that came back above is not quite right as it doesn’t take into account employment.  See attached definition.

Raised on behalf of Marc Rodrigeuz at the RNLI

**Comment by ikhapova** [comment] 2019-02-15 18:17
Closing as the issue is not relevant for Collaborate framework - this is a product issue for AX 2012.

**Closed by ikhapova** 2019-02-15 18:17 UTC
