### ISSUE TITLE
Difference in lookup and manual input

### ISSUE THREAD

**Issue by 4PSSupport** [MicrosoftDocs/MicrosoftCollaboratePortal#100] opened 2018-07-25 13:50 UTC
In NAV2017 in the Payment Journal there is a difference between lookup and manual input of the Applies-to Doc.No.. When the lookup is used to select an invoice or credit memo the debit and credit amounts are automatically filled with the remaining amount of the selected Document. When entering the Applies-to Doc. No manually the amount fields are not filled. There should be no difference in calculating the amount fields between direct input or lookup.

**Comment by ikhapova** [comment] 2018-07-28 04:55
Thank you for the feedback. It would be best to escalate this through Dynamics support.
Closing as the issue is not related to Collaborate.

**Closed by ikhapova** 2018-07-28 04:55 UTC
